INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (116, 0, 'Technical Detail Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (312, 959, 'Short Personality Assessment (Spanish)');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (34, 0, 'IC Behavioral Assessment');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (14, 0, 'SL Behavioral Assessment');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (62, 0, 'Supervisor Skills Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (101, 0, 'Cognitive Ability Logic Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (39, 0, 'IC Ability');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (45, 0, 'Sales Ability');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (104, 0, 'Short Personality Assessment');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (111, 0, 'Reading Comprehension Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (109, 0, 'Basic Sales Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (106, 0, 'Hard Math Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (103, 0, 'Simple Math Test ');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (99, 0, 'Telemarketing Skills Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (107, 0, 'Easy Math Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (112, 0, 'Integrity Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (232, 0, 'Short Detail Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (36, 0, 'Logic Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (108, 0, 'Writing Skills Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (114, 0, 'Verbal Reasoning Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (275, 113, 'Custom Assessment #1');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (113, 0, 'Numerical Reasoning Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (59, 0, 'Administrative Detail Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (276, 32, 'custom test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (110, 1, 'Product Sales Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (270, 3, 'custom_test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (274, 32, 'Test custom 1');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (268, 0, 'Excel 2016 Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (279, 826, 'Custom Assessment');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (35, 0, 'Big Five Personality Assessment');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (100, 0, 'Matrix Reasoning Test');
INSERT INTO public.assessment (assessment_id, company_id, assessment_name) VALUES (314, 30, 'BGSU Big Five Assessment');