INSERT INTO public.company (company_id, company_name) VALUES (498, 'Uber Company');
INSERT INTO public.company (company_id, company_name) VALUES (591, 'фыв');
INSERT INTO public.company (company_id, company_name) VALUES (598, 'hhyyhhfgfg');
INSERT INTO public.company (company_id, company_name) VALUES (604, 'sdfsdfsdf');
INSERT INTO public.company (company_id, company_name) VALUES (542, 'Dastan');
INSERT INTO public.company (company_id, company_name) VALUES (556, 'вавава');
INSERT INTO public.company (company_id, company_name) VALUES (562, 'fsdgdsfg');
INSERT INTO public.company (company_id, company_name) VALUES (662, 'Silver Lake Dental');
INSERT INTO public.company (company_id, company_name) VALUES (605, 'долдол');
INSERT INTO public.company (company_id, company_name) VALUES (635, 'Vitalii2');
INSERT INTO public.company (company_id, company_name) VALUES (567, 'lololololol');
INSERT INTO public.company (company_id, company_name) VALUES (568, 'wewer');
INSERT INTO public.company (company_id, company_name) VALUES (646, 'Louie''s Home Center');
INSERT INTO public.company (company_id, company_name) VALUES (581, 'Prod company');
INSERT INTO public.company (company_id, company_name) VALUES (49, 'TASK 2274-company test');
INSERT INTO public.company (company_id, company_name) VALUES (677, 'Murphy Healthcare');
INSERT INTO public.company (company_id, company_name) VALUES (340, '#3');
INSERT INTO public.company (company_id, company_name) VALUES (657, 'Mayweather Boxing  & Fitness');
INSERT INTO public.company (company_id, company_name) VALUES (614, 'Zentility');
INSERT INTO public.company (company_id, company_name) VALUES (792, 'AtlasDev');
INSERT INTO public.company (company_id, company_name) VALUES (348, 'vdm49835@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (624, 'Harmony Beef');
INSERT INTO public.company (company_id, company_name) VALUES (630, 'Weston''s Fake Company 4');
INSERT INTO public.company (company_id, company_name) VALUES (776, 'CPA Solutions');
INSERT INTO public.company (company_id, company_name) VALUES (682, 'Limestone Property Management');
INSERT INTO public.company (company_id, company_name) VALUES (667, 'Beon Retirement');
INSERT INTO public.company (company_id, company_name) VALUES (672, 'zzzzzzzzzzzzzzzzzz');
INSERT INTO public.company (company_id, company_name) VALUES (687, 'Acheson Builders');
INSERT INTO public.company (company_id, company_name) VALUES (782, 'Gopure Beauty');
INSERT INTO public.company (company_id, company_name) VALUES (771, 'All County Exteriors - Enterprises ');
INSERT INTO public.company (company_id, company_name) VALUES (766, 'Talent Grader');
INSERT INTO public.company (company_id, company_name) VALUES (731, 'xjg55983@zwoho.com');
INSERT INTO public.company (company_id, company_name) VALUES (741, 'Weston''s Fake Company 8');
INSERT INTO public.company (company_id, company_name) VALUES (765, 'Talent Grader 1');
INSERT INTO public.company (company_id, company_name) VALUES (759, 'TG-1');
INSERT INTO public.company (company_id, company_name) VALUES (793, 'Chatham');
INSERT INTO public.company (company_id, company_name) VALUES (787, 'August Roofing and Solar');
INSERT INTO public.company (company_id, company_name) VALUES (802, 'Medicreations');
INSERT INTO public.company (company_id, company_name) VALUES (805, 'Alliance BanCard');
INSERT INTO public.company (company_id, company_name) VALUES (798, 'Homeoptions');
INSERT INTO public.company (company_id, company_name) VALUES (727, 'Hansel Auto Group');
INSERT INTO public.company (company_id, company_name) VALUES (808, 'Grace Community Church');
INSERT INTO public.company (company_id, company_name) VALUES (810, 'MPower');
INSERT INTO public.company (company_id, company_name) VALUES (812, 'City of Seattle');
INSERT INTO public.company (company_id, company_name) VALUES (586, 'email test2');
INSERT INTO public.company (company_id, company_name) VALUES (654, 'Katrina Eileen');
INSERT INTO public.company (company_id, company_name) VALUES (351, 'zgr35223@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (814, 'Test_StatusColor_v2');
INSERT INTO public.company (company_id, company_name) VALUES (818, 'COO at Agape Development');
INSERT INTO public.company (company_id, company_name) VALUES (966, 'neverwinter');
INSERT INTO public.company (company_id, company_name) VALUES (344, '#7');
INSERT INTO public.company (company_id, company_name) VALUES (345, '#8');
INSERT INTO public.company (company_id, company_name) VALUES (346, '#9');
INSERT INTO public.company (company_id, company_name) VALUES (619, 'And Two');
INSERT INTO public.company (company_id, company_name) VALUES (354, 'zgr35223@eoopy.com3');
INSERT INTO public.company (company_id, company_name) VALUES (610, '123321123');
INSERT INTO public.company (company_id, company_name) VALUES (225, 'ss');
INSERT INTO public.company (company_id, company_name) VALUES (543, 'EON');
INSERT INTO public.company (company_id, company_name) VALUES (599, 'saddas213123');
INSERT INTO public.company (company_id, company_name) VALUES (668, 'dasdqweqwe');
INSERT INTO public.company (company_id, company_name) VALUES (548, 'Quasar company');
INSERT INTO public.company (company_id, company_name) VALUES (557, 'kikik');
INSERT INTO public.company (company_id, company_name) VALUES (606, 'https://temp-mail.org/ru/asdasd');
INSERT INTO public.company (company_id, company_name) VALUES (569, 'nnnnnn');
INSERT INTO public.company (company_id, company_name) VALUES (575, 'WAAAAAGH!');
INSERT INTO public.company (company_id, company_name) VALUES (688, 'Smart Systems Technology ');
INSERT INTO public.company (company_id, company_name) VALUES (243, 'asdfadf11111111111');
INSERT INTO public.company (company_id, company_name) VALUES (783, 'Greenville County Library System');
INSERT INTO public.company (company_id, company_name) VALUES (1, 'The Hire Talent TESTING');
INSERT INTO public.company (company_id, company_name) VALUES (587, 'email test3');
INSERT INTO public.company (company_id, company_name) VALUES (673, 'hookah club');
INSERT INTO public.company (company_id, company_name) VALUES (636, 'Vitalii3');
INSERT INTO public.company (company_id, company_name) VALUES (327, 'lqs39138@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (647, 'Stevens Global Logistics');
INSERT INTO public.company (company_id, company_name) VALUES (678, 'SAI MedPartners');
INSERT INTO public.company (company_id, company_name) VALUES (653, 'Weston''s Fake Company 5');
INSERT INTO public.company (company_id, company_name) VALUES (732, 'Talent Grade');
INSERT INTO public.company (company_id, company_name) VALUES (663, 'Veterans Healthcare Supply Solutions');
INSERT INTO public.company (company_id, company_name) VALUES (683, 'The Hire Talent DEMO');
INSERT INTO public.company (company_id, company_name) VALUES (631, 'Darren Robertson Homes');
INSERT INTO public.company (company_id, company_name) VALUES (723, 'Onco, Inc.');
INSERT INTO public.company (company_id, company_name) VALUES (366, 'zgr35223@eoopy.com18');
INSERT INTO public.company (company_id, company_name) VALUES (737, 'Talent Grade 3');
INSERT INTO public.company (company_id, company_name) VALUES (728, 'ypb84762@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (760, 'nrs41447@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (767, 'Nutraceutical Systems International');
INSERT INTO public.company (company_id, company_name) VALUES (772, 'Center Pointe');
INSERT INTO public.company (company_id, company_name) VALUES (615, 'Statuses test company');
INSERT INTO public.company (company_id, company_name) VALUES (658, 'CMM Construction');
INSERT INTO public.company (company_id, company_name) VALUES (30, 'Wimbush & Associates, Inc.');
INSERT INTO public.company (company_id, company_name) VALUES (788, 'Gates Mineral Company');
INSERT INTO public.company (company_id, company_name) VALUES (799, 'PRECISION IMAGE ANALYSIS, INC.');
INSERT INTO public.company (company_id, company_name) VALUES (777, 'ivan.beliakovTest');
INSERT INTO public.company (company_id, company_name) VALUES (642, 'nrg01609@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (742, 'Fake Company Name');
INSERT INTO public.company (company_id, company_name) VALUES (365, 'zgr35223@eoopy.com17');
INSERT INTO public.company (company_id, company_name) VALUES (363, 'zgr35223@eoopy.com15');
INSERT INTO public.company (company_id, company_name) VALUES (362, 'zgr35223@eoopy.com14');
INSERT INTO public.company (company_id, company_name) VALUES (361, 'zgr35223@eoopy.com13');
INSERT INTO public.company (company_id, company_name) VALUES (360, 'zgr35223@eoopy.com12');
INSERT INTO public.company (company_id, company_name) VALUES (358, 'zgr35223@eoopy.com10');
INSERT INTO public.company (company_id, company_name) VALUES (356, 'zgr35223@eoopy.com6');
INSERT INTO public.company (company_id, company_name) VALUES (355, 'zgr35223@eoopy.com4');
INSERT INTO public.company (company_id, company_name) VALUES (332, 'qrb01768@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (246, '12345');
INSERT INTO public.company (company_id, company_name) VALUES (341, '#4');
INSERT INTO public.company (company_id, company_name) VALUES (343, '#6');
INSERT INTO public.company (company_id, company_name) VALUES (582, 'ivan.beliakov@introlab-systems.com1111');
INSERT INTO public.company (company_id, company_name) VALUES (349, 'zrg38820@bcaoo.com');
INSERT INTO public.company (company_id, company_name) VALUES (240, 'выафываasdasda11111111111');
INSERT INTO public.company (company_id, company_name) VALUES (252, 's1');
INSERT INTO public.company (company_id, company_name) VALUES (600, 'sdf213');
INSERT INTO public.company (company_id, company_name) VALUES (488, 'QA Company #2');
INSERT INTO public.company (company_id, company_name) VALUES (724, 'Associated Mechanical ');
INSERT INTO public.company (company_id, company_name) VALUES (601, 'sdfsdf123');
INSERT INTO public.company (company_id, company_name) VALUES (538, 'ZhovtonogTest');
INSERT INTO public.company (company_id, company_name) VALUES (558, 'sdfsdf');
INSERT INTO public.company (company_id, company_name) VALUES (444, 'sssssasdfa');
INSERT INTO public.company (company_id, company_name) VALUES (564, 'wwww');
INSERT INTO public.company (company_id, company_name) VALUES (637, '10344 Destiny USA Dr Space B207');
INSERT INTO public.company (company_id, company_name) VALUES (576, 'enter');
INSERT INTO public.company (company_id, company_name) VALUES (583, 'xqn51763@zwoho.com');
INSERT INTO public.company (company_id, company_name) VALUES (588, 'Matt Blanton');
INSERT INTO public.company (company_id, company_name) VALUES (607, 'gkhjgjk');
INSERT INTO public.company (company_id, company_name) VALUES (733, 'Talent Grade 2');
INSERT INTO public.company (company_id, company_name) VALUES (224, '234123451234');
INSERT INTO public.company (company_id, company_name) VALUES (611, '1_1');
INSERT INTO public.company (company_id, company_name) VALUES (616, 'Sss');
INSERT INTO public.company (company_id, company_name) VALUES (560, 'asdfasdfsadf');
INSERT INTO public.company (company_id, company_name) VALUES (784, 'Statuses Corp. (test)');
INSERT INTO public.company (company_id, company_name) VALUES (549, 'My Company Test');
INSERT INTO public.company (company_id, company_name) VALUES (689, 'SpaceManager Closets ');
INSERT INTO public.company (company_id, company_name) VALUES (643, 'linori5851@revutap.com');
INSERT INTO public.company (company_id, company_name) VALUES (679, 'System Pavers');
INSERT INTO public.company (company_id, company_name) VALUES (648, 'Comp Stat Test');
INSERT INTO public.company (company_id, company_name) VALUES (632, 'Meomi Lighting');
INSERT INTO public.company (company_id, company_name) VALUES (669, 'djahgduqwefvhqbwgfeqhwuyetruyqw');
INSERT INTO public.company (company_id, company_name) VALUES (684, 'CAMP Systems');
INSERT INTO public.company (company_id, company_name) VALUES (664, 'Kahana Feld');
INSERT INTO public.company (company_id, company_name) VALUES (729, 'ejb92259@zwoho.com');
INSERT INTO public.company (company_id, company_name) VALUES (738, 'Stride Autism Centers');
INSERT INTO public.company (company_id, company_name) VALUES (659, 'Nylas test');
INSERT INTO public.company (company_id, company_name) VALUES (743, 'The Hire Talent Performance Tool');
INSERT INTO public.company (company_id, company_name) VALUES (761, 'TG-2');
INSERT INTO public.company (company_id, company_name) VALUES (768, 'Test Company/');
INSERT INTO public.company (company_id, company_name) VALUES (773, 'Christian Union');
INSERT INTO public.company (company_id, company_name) VALUES (674, 'Domain test');
INSERT INTO public.company (company_id, company_name) VALUES (143, 'TEST COMP 123');
INSERT INTO public.company (company_id, company_name) VALUES (570, '100%');
INSERT INTO public.company (company_id, company_name) VALUES (621, 'And Three');
INSERT INTO public.company (company_id, company_name) VALUES (251, 'asfasdfadsfasdfasdfasdfasdfasdfasdf');
INSERT INTO public.company (company_id, company_name) VALUES (250, 'asdfadf 12312312322');
INSERT INTO public.company (company_id, company_name) VALUES (249, 'asdfadf 1231231232');
INSERT INTO public.company (company_id, company_name) VALUES (248, 'asdfadf 123123123');
INSERT INTO public.company (company_id, company_name) VALUES (227, 'asdfadsfasdfasdfa');
INSERT INTO public.company (company_id, company_name) VALUES (226, 'asdfadfфывафыв');
INSERT INTO public.company (company_id, company_name) VALUES (329, 'uku87580@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (367, 'zgr35223@eoopy.com19');
INSERT INTO public.company (company_id, company_name) VALUES (364, 'zgr35223@eoopy.com16');
INSERT INTO public.company (company_id, company_name) VALUES (359, 'zgr35223@eoopy.com11');
INSERT INTO public.company (company_id, company_name) VALUES (350, 'msu42925@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (357, 'zgr35223@eoopy.com7');
INSERT INTO public.company (company_id, company_name) VALUES (342, '#5');
INSERT INTO public.company (company_id, company_name) VALUES (907, 'Jarrett Construction');
INSERT INTO public.company (company_id, company_name) VALUES (487, 'QA Company #1');
INSERT INTO public.company (company_id, company_name) VALUES (241, 'new company6');
INSERT INTO public.company (company_id, company_name) VALUES (330, 'Reg User 1');
INSERT INTO public.company (company_id, company_name) VALUES (253, 'new company9');
INSERT INTO public.company (company_id, company_name) VALUES (254, 's123');
INSERT INTO public.company (company_id, company_name) VALUES (255, 's111');
INSERT INTO public.company (company_id, company_name) VALUES (565, 'hhhhhhhhhhh');
INSERT INTO public.company (company_id, company_name) VALUES (612, '1312edase4123');
INSERT INTO public.company (company_id, company_name) VALUES (680, 'GIGAMONSTER');
INSERT INTO public.company (company_id, company_name) VALUES (602, 'jjuuj');
INSERT INTO public.company (company_id, company_name) VALUES (533, 'The Hire Talent');
INSERT INTO public.company (company_id, company_name) VALUES (571, '101%');
INSERT INTO public.company (company_id, company_name) VALUES (627, 'DreamSpring');
INSERT INTO public.company (company_id, company_name) VALUES (77, 're-re-check1');
INSERT INTO public.company (company_id, company_name) VALUES (584, 'Fake Company 4');
INSERT INTO public.company (company_id, company_name) VALUES (649, 'OC Owner User Group');
INSERT INTO public.company (company_id, company_name) VALUES (660, 'Matic');
INSERT INTO public.company (company_id, company_name) VALUES (589, 'Google OAuth Test');
INSERT INTO public.company (company_id, company_name) VALUES (546, 'hhhh');
INSERT INTO public.company (company_id, company_name) VALUES (734, 'lfu58049@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (553, 'Hey iches');
INSERT INTO public.company (company_id, company_name) VALUES (559, 'gihef37422@laraskey.com');
INSERT INTO public.company (company_id, company_name) VALUES (552, 'Abahaha');
INSERT INTO public.company (company_id, company_name) VALUES (608, 'Security Review Test Company ');
INSERT INTO public.company (company_id, company_name) VALUES (113, 'QATC');
INSERT INTO public.company (company_id, company_name) VALUES (539, 'ZhovtonogTest2');
INSERT INTO public.company (company_id, company_name) VALUES (633, 'Proscaff Enterprises');
INSERT INTO public.company (company_id, company_name) VALUES (622, 'Example Account');
INSERT INTO public.company (company_id, company_name) VALUES (725, 'R & R Window Contractors');
INSERT INTO public.company (company_id, company_name) VALUES (638, 'Vitality');
INSERT INTO public.company (company_id, company_name) VALUES (644, 'Ref 1');
INSERT INTO public.company (company_id, company_name) VALUES (665, 'Number');
INSERT INTO public.company (company_id, company_name) VALUES (730, 'yefono3146@nnacell.com');
INSERT INTO public.company (company_id, company_name) VALUES (685, 'Bertrand''s Music Enterprise Inc.');
INSERT INTO public.company (company_id, company_name) VALUES (655, 'Rite-temp');
INSERT INTO public.company (company_id, company_name) VALUES (3, 'Kanava');
INSERT INTO public.company (company_id, company_name) VALUES (670, 'dfasdasdasd');
INSERT INTO public.company (company_id, company_name) VALUES (690, 'Capitol Bridge');
INSERT INTO public.company (company_id, company_name) VALUES (675, 'shisha bar');
INSERT INTO public.company (company_id, company_name) VALUES (744, 'Talent Grader Example');
INSERT INTO public.company (company_id, company_name) VALUES (739, '7 Seventy');
INSERT INTO public.company (company_id, company_name) VALUES (763, 'TG-4');
INSERT INTO public.company (company_id, company_name) VALUES (762, 'TG-3');
INSERT INTO public.company (company_id, company_name) VALUES (769, 'Talent Grade 4');
INSERT INTO public.company (company_id, company_name) VALUES (774, 'California Book Services');
INSERT INTO public.company (company_id, company_name) VALUES (780, 'Funtech');
INSERT INTO public.company (company_id, company_name) VALUES (617, 'Status Test');
INSERT INTO public.company (company_id, company_name) VALUES (803, 'CH Evans Roofing');
INSERT INTO public.company (company_id, company_name) VALUES (800, 'Midwest Aerospace Ltd.');
INSERT INTO public.company (company_id, company_name) VALUES (806, 'BC Treaty Commission');
INSERT INTO public.company (company_id, company_name) VALUES (796, 'Access Test');
INSERT INTO public.company (company_id, company_name) VALUES (235, 'asss');
INSERT INTO public.company (company_id, company_name) VALUES (238, 'выафыва');
INSERT INTO public.company (company_id, company_name) VALUES (239, 'выафываasdasda');
INSERT INTO public.company (company_id, company_name) VALUES (208, 'new company5');
INSERT INTO public.company (company_id, company_name) VALUES (211, 's');
INSERT INTO public.company (company_id, company_name) VALUES (401, 'One More Fake Company');
INSERT INTO public.company (company_id, company_name) VALUES (412, 'Uber#2');
INSERT INTO public.company (company_id, company_name) VALUES (202, 'Shinra Electric Power Company');
INSERT INTO public.company (company_id, company_name) VALUES (203, 'saraiev company 19/08');
INSERT INTO public.company (company_id, company_name) VALUES (204, 'new company');
INSERT INTO public.company (company_id, company_name) VALUES (205, 'new company2');
INSERT INTO public.company (company_id, company_name) VALUES (206, 'new company3');
INSERT INTO public.company (company_id, company_name) VALUES (388, 'osz42071@bcaoo.com1');
INSERT INTO public.company (company_id, company_name) VALUES (392, 'Fake Company');
INSERT INTO public.company (company_id, company_name) VALUES (484, 'ivan.beliakov.888');
INSERT INTO public.company (company_id, company_name) VALUES (328, 'new company11');
INSERT INTO public.company (company_id, company_name) VALUES (482, 'ivan.beliakov');
INSERT INTO public.company (company_id, company_name) VALUES (493, 'Auto-Chlor Recruiting');
INSERT INTO public.company (company_id, company_name) VALUES (207, 'new company4');
INSERT INTO public.company (company_id, company_name) VALUES (272, 'sй121212');
INSERT INTO public.company (company_id, company_name) VALUES (387, 'osz42071@bcaoo.com');
INSERT INTO public.company (company_id, company_name) VALUES (48, 'TASK 2274');
INSERT INTO public.company (company_id, company_name) VALUES (400, 'Fake Company 3');
INSERT INTO public.company (company_id, company_name) VALUES (62, 'New Quasi-Companyf');
INSERT INTO public.company (company_id, company_name) VALUES (63, 'Arkham Technology');
INSERT INTO public.company (company_id, company_name) VALUES (33, 'Front company11');
INSERT INTO public.company (company_id, company_name) VALUES (36, 'test name for common statuses test');
INSERT INTO public.company (company_id, company_name) VALUES (39, 'New Quasi-Company');
INSERT INTO public.company (company_id, company_name) VALUES (41, 'David''s Fake Company');
INSERT INTO public.company (company_id, company_name) VALUES (42, 'Test company');
INSERT INTO public.company (company_id, company_name) VALUES (43, 'Test company 123');
INSERT INTO public.company (company_id, company_name) VALUES (44, 'Test company 1253');
INSERT INTO public.company (company_id, company_name) VALUES (47, 'TASK 2274-2');
INSERT INTO public.company (company_id, company_name) VALUES (17, 'TEST COMPANY1');
INSERT INTO public.company (company_id, company_name) VALUES (23, 'COMPANY1225');
INSERT INTO public.company (company_id, company_name) VALUES (486, 'test company for signup bug');
INSERT INTO public.company (company_id, company_name) VALUES (485, 'Another Test Company 3');
INSERT INTO public.company (company_id, company_name) VALUES (481, 'Test');
INSERT INTO public.company (company_id, company_name) VALUES (446, 'test company');
INSERT INTO public.company (company_id, company_name) VALUES (445, 'test.ibeliakov');
INSERT INTO public.company (company_id, company_name) VALUES (133, 'testset');
INSERT INTO public.company (company_id, company_name) VALUES (61, 'Weston Test Company 1');
INSERT INTO public.company (company_id, company_name) VALUES (222, '11');
INSERT INTO public.company (company_id, company_name) VALUES (214, '111');
INSERT INTO public.company (company_id, company_name) VALUES (232, '1111111111111111111111111111111111');
INSERT INTO public.company (company_id, company_name) VALUES (393, '124');
INSERT INTO public.company (company_id, company_name) VALUES (394, '125');
INSERT INTO public.company (company_id, company_name) VALUES (395, '126');
INSERT INTO public.company (company_id, company_name) VALUES (397, '127');
INSERT INTO public.company (company_id, company_name) VALUES (398, '128');
INSERT INTO public.company (company_id, company_name) VALUES (399, '129');
INSERT INTO public.company (company_id, company_name) VALUES (218, '22');
INSERT INTO public.company (company_id, company_name) VALUES (384, 'alh39962@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (479, 'another fake company2');
INSERT INTO public.company (company_id, company_name) VALUES (443, 'asdfas');
INSERT INTO public.company (company_id, company_name) VALUES (237, 'asdfasdfadfafadsfasdfa111');
INSERT INTO public.company (company_id, company_name) VALUES (236, 'asdfasdfadfafadsfasdfa');
INSERT INTO public.company (company_id, company_name) VALUES (231, 'asdfssssssss');
INSERT INTO public.company (company_id, company_name) VALUES (230, 'asdfasdf');
INSERT INTO public.company (company_id, company_name) VALUES (229, 'asdfassss');
INSERT INTO public.company (company_id, company_name) VALUES (228, 'asdfa');
INSERT INTO public.company (company_id, company_name) VALUES (221, 'asdfasdfasdf1111');
INSERT INTO public.company (company_id, company_name) VALUES (220, 'asdfasdfasdfasdfasdfasdfasfasdf');
INSERT INTO public.company (company_id, company_name) VALUES (217, 'asdfasdfasdfasda');
INSERT INTO public.company (company_id, company_name) VALUES (216, 'asdfasss');
INSERT INTO public.company (company_id, company_name) VALUES (213, 'asdfadsf');
INSERT INTO public.company (company_id, company_name) VALUES (210, 'asdfadf');
INSERT INTO public.company (company_id, company_name) VALUES (209, 'asdf');
INSERT INTO public.company (company_id, company_name) VALUES (496, 'aod93958@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (480, 'Billing Company #1');
INSERT INTO public.company (company_id, company_name) VALUES (38, 'Bogdan');
INSERT INTO public.company (company_id, company_name) VALUES (396, 'cm1');
INSERT INTO public.company (company_id, company_name) VALUES (60, 'Company#1');
INSERT INTO public.company (company_id, company_name) VALUES (59, 'COMPANY-11-06-20');
INSERT INTO public.company (company_id, company_name) VALUES (18, 'COMPANY145');
INSERT INTO public.company (company_id, company_name) VALUES (386, 'iqg54375@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (385, 'eqx23956@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (233, '1111111111111111111s111111111111111');
INSERT INTO public.company (company_id, company_name) VALUES (215, '12121212');
INSERT INTO public.company (company_id, company_name) VALUES (223, '12121212sss');
INSERT INTO public.company (company_id, company_name) VALUES (389, '123');
INSERT INTO public.company (company_id, company_name) VALUES (212, '2s');
INSERT INTO public.company (company_id, company_name) VALUES (219, '3');
INSERT INTO public.company (company_id, company_name) VALUES (234, 'ass');
INSERT INTO public.company (company_id, company_name) VALUES (247, 'new company8');
INSERT INTO public.company (company_id, company_name) VALUES (25, 'TEST COMPANY45');
INSERT INTO public.company (company_id, company_name) VALUES (26, 'Another company');
INSERT INTO public.company (company_id, company_name) VALUES (31, 'Weston''s Fake Company');
INSERT INTO public.company (company_id, company_name) VALUES (2, 'Red7 Systems, Inc');
INSERT INTO public.company (company_id, company_name) VALUES (264, 's1222222');
INSERT INTO public.company (company_id, company_name) VALUES (8, 'test2');
INSERT INTO public.company (company_id, company_name) VALUES (9, 'TEMP COMPANY');
INSERT INTO public.company (company_id, company_name) VALUES (10, 'TEST');
INSERT INTO public.company (company_id, company_name) VALUES (132, 'saraiev company 1');
INSERT INTO public.company (company_id, company_name) VALUES (304, 'ivan.beliakov@introlab-systems.com7');
INSERT INTO public.company (company_id, company_name) VALUES (305, 'ivan.beliakov@introlab-systems.com9');
INSERT INTO public.company (company_id, company_name) VALUES (306, 'ivan.beliakov@introlab-systems.com8');
INSERT INTO public.company (company_id, company_name) VALUES (307, 'ivan.beliakov@introlab-systems.com10');
INSERT INTO public.company (company_id, company_name) VALUES (308, 'ivan.beliakov@introlab-systems.com11');
INSERT INTO public.company (company_id, company_name) VALUES (309, 'ivan.beliakov@introlab-systems.com12');
INSERT INTO public.company (company_id, company_name) VALUES (310, 'ivan.beliakov@introlab-systems.com13');
INSERT INTO public.company (company_id, company_name) VALUES (311, 'ivan.beliakov@introlab-systems.com14');
INSERT INTO public.company (company_id, company_name) VALUES (312, 'ivan.beliakov@introlab-systems.com15');
INSERT INTO public.company (company_id, company_name) VALUES (313, 'drc60310@bcaoo.com');
INSERT INTO public.company (company_id, company_name) VALUES (314, 'wii69791@bcaoo.com');
INSERT INTO public.company (company_id, company_name) VALUES (317, 'spl62015@bcaoo.com');
INSERT INTO public.company (company_id, company_name) VALUES (319, 'ivan.beliakov@introlab-systems.com20');
INSERT INTO public.company (company_id, company_name) VALUES (290, 'fwo81096@bcaoo.com');
INSERT INTO public.company (company_id, company_name) VALUES (291, 'fwo81096@bcaoo.com1');
INSERT INTO public.company (company_id, company_name) VALUES (293, 'ivan.beliakov@introlab-systems.com');
INSERT INTO public.company (company_id, company_name) VALUES (298, 'ivan.beliakov@introlab-systems.com1');
INSERT INTO public.company (company_id, company_name) VALUES (299, 'ivan.beliakov@introlab-systems.com2');
INSERT INTO public.company (company_id, company_name) VALUES (300, 'ivan.beliakov@introlab-systems.com3');
INSERT INTO public.company (company_id, company_name) VALUES (301, 'ivan.beliakov@introlab-systems.com4');
INSERT INTO public.company (company_id, company_name) VALUES (302, 'ivan.beliakov@introlab-systems.com5');
INSERT INTO public.company (company_id, company_name) VALUES (303, 'ivan.beliakov@introlab-systems.com6');
INSERT INTO public.company (company_id, company_name) VALUES (273, 's11111112323232');
INSERT INTO public.company (company_id, company_name) VALUES (274, 'kfsdakljsdfakljsda');
INSERT INTO public.company (company_id, company_name) VALUES (278, 'new company10');
INSERT INTO public.company (company_id, company_name) VALUES (76, 're-re-check');
INSERT INTO public.company (company_id, company_name) VALUES (75, 're-check');
INSERT INTO public.company (company_id, company_name) VALUES (257, 's123123123');
INSERT INTO public.company (company_id, company_name) VALUES (261, 's123456');
INSERT INTO public.company (company_id, company_name) VALUES (263, 's0');
INSERT INTO public.company (company_id, company_name) VALUES (265, 's123й');
INSERT INTO public.company (company_id, company_name) VALUES (266, 's1212121212121');
INSERT INTO public.company (company_id, company_name) VALUES (267, 's0998');
INSERT INTO public.company (company_id, company_name) VALUES (242, 'new company7');
INSERT INTO public.company (company_id, company_name) VALUES (270, 's0988888');
INSERT INTO public.company (company_id, company_name) VALUES (271, 'йуц1');
INSERT INTO public.company (company_id, company_name) VALUES (371, 'ttz66925@bcaoo.com22');
INSERT INTO public.company (company_id, company_name) VALUES (372, 'ttz66925@bcaoo.com');
INSERT INTO public.company (company_id, company_name) VALUES (373, 'ttz66925@bcaoo.com1');
INSERT INTO public.company (company_id, company_name) VALUES (374, 'ttz66925@bcaoo.com2');
INSERT INTO public.company (company_id, company_name) VALUES (78, 'Test Company 2');
INSERT INTO public.company (company_id, company_name) VALUES (331, 'test.test');
INSERT INTO public.company (company_id, company_name) VALUES (277, 'asdfadf1212112');
INSERT INTO public.company (company_id, company_name) VALUES (269, '1111');
INSERT INTO public.company (company_id, company_name) VALUES (554, 'lololol');
INSERT INTO public.company (company_id, company_name) VALUES (268, '11111111');
INSERT INTO public.company (company_id, company_name) VALUES (262, '12345654');
INSERT INTO public.company (company_id, company_name) VALUES (540, 'aasdfafdasfasd@adsfasdf.asdfa');
INSERT INTO public.company (company_id, company_name) VALUES (316, 'ugw73928@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (297, 'tnh50849@cuoly.com1');
INSERT INTO public.company (company_id, company_name) VALUES (296, 'tnh50849@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (295, 'bxb22132@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (289, 'bky05432@cuoly.com2');
INSERT INTO public.company (company_id, company_name) VALUES (288, 'bky05432@cuoly.com11');
INSERT INTO public.company (company_id, company_name) VALUES (287, 'bky05432@cuoly.com1');
INSERT INTO public.company (company_id, company_name) VALUES (283, 'bky05432@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (279, 'tcr56417@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (376, 'ysf03153@eoopy.com23');
INSERT INTO public.company (company_id, company_name) VALUES (375, 'ysf03153@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (370, 'zgr35223@eoopy.com22');
INSERT INTO public.company (company_id, company_name) VALUES (369, 'zgr35223@eoopy.com21');
INSERT INTO public.company (company_id, company_name) VALUES (368, 'zgr35223@eoopy.com20');
INSERT INTO public.company (company_id, company_name) VALUES (318, 'god90313@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (315, 'kvg30308@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (294, 'cqk68268@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (256, '1212121');
INSERT INTO public.company (company_id, company_name) VALUES (259, '12334');
INSERT INTO public.company (company_id, company_name) VALUES (258, '123456');
INSERT INTO public.company (company_id, company_name) VALUES (260, '1234565');
INSERT INTO public.company (company_id, company_name) VALUES (276, '324789jkfadsklsadf');
INSERT INTO public.company (company_id, company_name) VALUES (275, '4321234515123');
INSERT INTO public.company (company_id, company_name) VALUES (380, 'znmcnjokiknymbyyaa@etochq.com');
INSERT INTO public.company (company_id, company_name) VALUES (381, 'emjvhooqpdvojzjddm@tsyefn.com');
INSERT INTO public.company (company_id, company_name) VALUES (382, 'krtfcirlhsvbswsxwc@twzhhq.online');
INSERT INTO public.company (company_id, company_name) VALUES (383, 'gywhsixjajsizexbul@etochq.com');
INSERT INTO public.company (company_id, company_name) VALUES (500, 'QATC Prod.');
INSERT INTO public.company (company_id, company_name) VALUES (534, 'Contractor Staffing Source');
INSERT INTO public.company (company_id, company_name) VALUES (661, 'Spherexx');
INSERT INTO public.company (company_id, company_name) VALUES (603, 'вапыфыаdfs');
INSERT INTO public.company (company_id, company_name) VALUES (541, 'lol');
INSERT INTO public.company (company_id, company_name) VALUES (555, 'dxfgsdfsfd');
INSERT INTO public.company (company_id, company_name) VALUES (561, 'dsf');
INSERT INTO public.company (company_id, company_name) VALUES (797, '2222222222222');
INSERT INTO public.company (company_id, company_name) VALUES (629, 'And Five');
INSERT INTO public.company (company_id, company_name) VALUES (786, 'Pioneer Plumbing Heating and Cooling');
INSERT INTO public.company (company_id, company_name) VALUES (578, 'Smoke');
INSERT INTO public.company (company_id, company_name) VALUES (666, 'Omega Packaging');
INSERT INTO public.company (company_id, company_name) VALUES (579, 'SmokeOne');
INSERT INTO public.company (company_id, company_name) VALUES (735, 'cru87554@eoopy.com');
INSERT INTO public.company (company_id, company_name) VALUES (580, 'First');
INSERT INTO public.company (company_id, company_name) VALUES (758, 'Love To Know');
INSERT INTO public.company (company_id, company_name) VALUES (590, 'Whales');
INSERT INTO public.company (company_id, company_name) VALUES (623, 'Weston''s Fake Company 3');
INSERT INTO public.company (company_id, company_name) VALUES (671, 'dhgasjhkdgsjhkdgjk');
INSERT INTO public.company (company_id, company_name) VALUES (618, 'And One');
INSERT INTO public.company (company_id, company_name) VALUES (676, 'hokaido club');
INSERT INTO public.company (company_id, company_name) VALUES (628, 'TES!@#$%^&*');
INSERT INTO public.company (company_id, company_name) VALUES (378, 'ysf03153@eoopy.com30');
INSERT INTO public.company (company_id, company_name) VALUES (764, 'TG-5');
INSERT INTO public.company (company_id, company_name) VALUES (681, 'Crown Cards');
INSERT INTO public.company (company_id, company_name) VALUES (645, 'Ref 2');
INSERT INTO public.company (company_id, company_name) VALUES (639, 'Darren Robertson');
INSERT INTO public.company (company_id, company_name) VALUES (656, 'Ascentris');
INSERT INTO public.company (company_id, company_name) VALUES (585, 'emaril test');
INSERT INTO public.company (company_id, company_name) VALUES (726, 'DWP');
INSERT INTO public.company (company_id, company_name) VALUES (609, '1');
INSERT INTO public.company (company_id, company_name) VALUES (686, 'Statuses test');
INSERT INTO public.company (company_id, company_name) VALUES (770, 'Agape Development');
INSERT INTO public.company (company_id, company_name) VALUES (547, 'Test2222');
INSERT INTO public.company (company_id, company_name) VALUES (775, 'Weston''s Fake Company 9');
INSERT INTO public.company (company_id, company_name) VALUES (781, 'Funtech2');
INSERT INTO public.company (company_id, company_name) VALUES (801, 'Professional Services Search');
INSERT INTO public.company (company_id, company_name) VALUES (804, 'Newman Tractor - Verona');
INSERT INTO public.company (company_id, company_name) VALUES (811, 'Bristol Community College');
INSERT INTO public.company (company_id, company_name) VALUES (807, 'The MH Companies');
INSERT INTO public.company (company_id, company_name) VALUES (809, 'SECONDARY MARKETING SERVICES');
INSERT INTO public.company (company_id, company_name) VALUES (566, 'testtestest');
INSERT INTO public.company (company_id, company_name) VALUES (813, 'Test_StatusColor');
INSERT INTO public.company (company_id, company_name) VALUES (815, 'Test_StatusColor_v3');
INSERT INTO public.company (company_id, company_name) VALUES (817, 'Keller CPAs');
INSERT INTO public.company (company_id, company_name) VALUES (819, 'FAB&T');
INSERT INTO public.company (company_id, company_name) VALUES (820, 'Mistake Company');
INSERT INTO public.company (company_id, company_name) VALUES (821, 'llojibwe');
INSERT INTO public.company (company_id, company_name) VALUES (816, 'Test_StatusColor_v4');
INSERT INTO public.company (company_id, company_name) VALUES (740, 'test def bill');
INSERT INTO public.company (company_id, company_name) VALUES (823, 'RegenMed');
INSERT INTO public.company (company_id, company_name) VALUES (377, 'ysf03153@eoopy.com12312');
INSERT INTO public.company (company_id, company_name) VALUES (353, 'zgr35223@eoopy.com2');
INSERT INTO public.company (company_id, company_name) VALUES (352, 'zgr35223@eoopy.com1');
INSERT INTO public.company (company_id, company_name) VALUES (379, '321');
INSERT INTO public.company (company_id, company_name) VALUES (634, 'afdsfsad');
INSERT INTO public.company (company_id, company_name) VALUES (822, 'Fazzolari Custom Homes & Renovations');
INSERT INTO public.company (company_id, company_name) VALUES (824, 'Lynniamfarms');
INSERT INTO public.company (company_id, company_name) VALUES (825, 'Weston''s Fake Company 10');
INSERT INTO public.company (company_id, company_name) VALUES (901, 'Peter Johnson Builders');
INSERT INTO public.company (company_id, company_name) VALUES (896, 'aaron demo');
INSERT INTO public.company (company_id, company_name) VALUES (827, 'MBX Systems');
INSERT INTO public.company (company_id, company_name) VALUES (828, 'Gordon College');
INSERT INTO public.company (company_id, company_name) VALUES (863, 'CED GreenTech');
INSERT INTO public.company (company_id, company_name) VALUES (829, 'Evans Companies');
INSERT INTO public.company (company_id, company_name) VALUES (854, 'Snell & Wilmer L.L.P.');
INSERT INTO public.company (company_id, company_name) VALUES (830, 'RbA of Wyoming');
INSERT INTO public.company (company_id, company_name) VALUES (831, 'Boss');
INSERT INTO public.company (company_id, company_name) VALUES (856, 'xbr11789@zwoho.com');
INSERT INTO public.company (company_id, company_name) VALUES (844, 'Moulton & Hardin, Inc.');
INSERT INTO public.company (company_id, company_name) VALUES (833, 'Freedom Racing');
INSERT INTO public.company (company_id, company_name) VALUES (834, 'TK CPA');
INSERT INTO public.company (company_id, company_name) VALUES (826, 'Weston''s Fake Company 11');
INSERT INTO public.company (company_id, company_name) VALUES (835, 'MONTES MEDICAL GROUP, INC');
INSERT INTO public.company (company_id, company_name) VALUES (832, 'Harbinger Group');
INSERT INTO public.company (company_id, company_name) VALUES (853, 'cxl76643@cuoly.com');
INSERT INTO public.company (company_id, company_name) VALUES (838, 'Keller | Lenkner');
INSERT INTO public.company (company_id, company_name) VALUES (846, 'Ambit Inc');
INSERT INTO public.company (company_id, company_name) VALUES (839, 'Shamrock Trading Corp.');
INSERT INTO public.company (company_id, company_name) VALUES (840, 'Baker Tilly Inc');
INSERT INTO public.company (company_id, company_name) VALUES (841, 'Christine Valmy, Inc');
INSERT INTO public.company (company_id, company_name) VALUES (847, 'Stephanie''s Recruiting Reqs');
INSERT INTO public.company (company_id, company_name) VALUES (842, 'MOBIS PARTS AMERICA');
INSERT INTO public.company (company_id, company_name) VALUES (843, 'University of Beer');
INSERT INTO public.company (company_id, company_name) VALUES (857, 'Tracepoint');
INSERT INTO public.company (company_id, company_name) VALUES (848, 'Haglid Engineering');
INSERT INTO public.company (company_id, company_name) VALUES (845, 'August Roofing Inc');
INSERT INTO public.company (company_id, company_name) VALUES (905, 'Dunbar Inc');
INSERT INTO public.company (company_id, company_name) VALUES (902, 'Gridley Company');
INSERT INTO public.company (company_id, company_name) VALUES (858, 'Korral Kool');
INSERT INTO public.company (company_id, company_name) VALUES (908, 'J&RS Build');
INSERT INTO public.company (company_id, company_name) VALUES (899, 'RW Scott Construction');
INSERT INTO public.company (company_id, company_name) VALUES (779, 'TheraTree Pediatric Therapy ');
INSERT INTO public.company (company_id, company_name) VALUES (903, 'Sacred Oak Homes');
INSERT INTO public.company (company_id, company_name) VALUES (898, 'Snowridge Remodeling');
INSERT INTO public.company (company_id, company_name) VALUES (900, 'Gilmore Building Co. ');
INSERT INTO public.company (company_id, company_name) VALUES (904, 'Custom Home Design');
INSERT INTO public.company (company_id, company_name) VALUES (897, 'ServePro9669');
INSERT INTO public.company (company_id, company_name) VALUES (859, 'TruAdvantage');
INSERT INTO public.company (company_id, company_name) VALUES (861, 'Test company 22');
INSERT INTO public.company (company_id, company_name) VALUES (860, 'Test login');
INSERT INTO public.company (company_id, company_name) VALUES (910, 'The Tech Stage');
INSERT INTO public.company (company_id, company_name) VALUES (909, 'Keystone Homes');
INSERT INTO public.company (company_id, company_name) VALUES (915, 'Orange County Deck');
INSERT INTO public.company (company_id, company_name) VALUES (913, 'Kitchen Tune Up PA');
INSERT INTO public.company (company_id, company_name) VALUES (927, 'CQC Home ');
INSERT INTO public.company (company_id, company_name) VALUES (945, 'Think Make Build ');
INSERT INTO public.company (company_id, company_name) VALUES (943, 'Everlast Epoxy');
INSERT INTO public.company (company_id, company_name) VALUES (925, 'Braswell Homes');
INSERT INTO public.company (company_id, company_name) VALUES (919, 'REZ Management');
INSERT INTO public.company (company_id, company_name) VALUES (947, 'UpCycle Builders');
INSERT INTO public.company (company_id, company_name) VALUES (916, 'Pizzolon Construction');
INSERT INTO public.company (company_id, company_name) VALUES (917, 'Riverbend Builders');
INSERT INTO public.company (company_id, company_name) VALUES (918, 'NCSWash');
INSERT INTO public.company (company_id, company_name) VALUES (912, 'Bramante Homes');
INSERT INTO public.company (company_id, company_name) VALUES (923, 'Aquilo Interiors');
INSERT INTO public.company (company_id, company_name) VALUES (937, 'H&H Builders Denver ');
INSERT INTO public.company (company_id, company_name) VALUES (930, 'Cronkhite Homes ');
INSERT INTO public.company (company_id, company_name) VALUES (932, 'Dovetail Group');
INSERT INTO public.company (company_id, company_name) VALUES (986, 'E Craft Georgia');
INSERT INTO public.company (company_id, company_name) VALUES (936, 'DryPaT LLC');
INSERT INTO public.company (company_id, company_name) VALUES (933, 'Godfrey Design Build ');
INSERT INTO public.company (company_id, company_name) VALUES (920, 'MA Restoration ');
INSERT INTO public.company (company_id, company_name) VALUES (939, 'JL Remodeling ');
INSERT INTO public.company (company_id, company_name) VALUES (934, 'Colorado Sunroom and Window');
INSERT INTO public.company (company_id, company_name) VALUES (948, 'Kaminski Construction');
INSERT INTO public.company (company_id, company_name) VALUES (942, 'Northland Design & Build ');
INSERT INTO public.company (company_id, company_name) VALUES (941, 'Northwest Heritage Renovations ');
INSERT INTO public.company (company_id, company_name) VALUES (985, 'FreeState Justice');
INSERT INTO public.company (company_id, company_name) VALUES (921, 'Alair Homes Plano');
INSERT INTO public.company (company_id, company_name) VALUES (931, 'Crownover Company ');
INSERT INTO public.company (company_id, company_name) VALUES (984, 'G Peterson Consulting Group');
INSERT INTO public.company (company_id, company_name) VALUES (987, 'ProHome');
INSERT INTO public.company (company_id, company_name) VALUES (949, 'New Heating and Cooling LLC');
INSERT INTO public.company (company_id, company_name) VALUES (959, 'Aaron Demo Videos');
INSERT INTO public.company (company_id, company_name) VALUES (952, 'Severn Woods  Fine Homes');
INSERT INTO public.company (company_id, company_name) VALUES (957, 'TMG Construction Management, Inc.');
INSERT INTO public.company (company_id, company_name) VALUES (958, 'Aamodt Plumb');
INSERT INTO public.company (company_id, company_name) VALUES (962, 'Trade Design Build');
INSERT INTO public.company (company_id, company_name) VALUES (981, 'Alair Homes: Marietta');
INSERT INTO public.company (company_id, company_name) VALUES (954, 'Waterton Construction Group');
INSERT INTO public.company (company_id, company_name) VALUES (960, 'Paradigm Building ');
INSERT INTO public.company (company_id, company_name) VALUES (956, 'Test campa123');
INSERT INTO public.company (company_id, company_name) VALUES (855, 'Test Company (Order)');
INSERT INTO public.company (company_id, company_name) VALUES (852, 'Statuses Order Test');
INSERT INTO public.company (company_id, company_name) VALUES (850, 'TimeZone final test');
INSERT INTO public.company (company_id, company_name) VALUES (849, 'TimeZone new test');
INSERT INTO public.company (company_id, company_name) VALUES (836, 'Statuses coloring Test');
INSERT INTO public.company (company_id, company_name) VALUES (45, 'Test c123ompany');
INSERT INTO public.company (company_id, company_name) VALUES (964, 'JKC, Inc.');
INSERT INTO public.company (company_id, company_name) VALUES (971, 'Beechen & Dill Homes');
INSERT INTO public.company (company_id, company_name) VALUES (976, 'Signum Architecture');
INSERT INTO public.company (company_id, company_name) VALUES (961, '3HTi');
INSERT INTO public.company (company_id, company_name) VALUES (862, 'Test company 23');
INSERT INTO public.company (company_id, company_name) VALUES (974, 'Associated Heating & Air Conditioning, Inc');
INSERT INTO public.company (company_id, company_name) VALUES (965, 'NorthMarq');
INSERT INTO public.company (company_id, company_name) VALUES (963, 'vsq91396@boofx.com');
INSERT INTO public.company (company_id, company_name) VALUES (967, 'Groman Group');
INSERT INTO public.company (company_id, company_name) VALUES (968, 'Kenny, Burns & McGill');
INSERT INTO public.company (company_id, company_name) VALUES (969, 'Ascent Consulting');
INSERT INTO public.company (company_id, company_name) VALUES (973, 'Imprenta Services');
INSERT INTO public.company (company_id, company_name) VALUES (955, 'Crownover Company');
INSERT INTO public.company (company_id, company_name) VALUES (975, 'Bay Build Design ');
INSERT INTO public.company (company_id, company_name) VALUES (497, 'ivan.beliakov@introlab-systems.com88');
INSERT INTO public.company (company_id, company_name) VALUES (979, 'Practical Nurse Program Southeastern Regional School District');
INSERT INTO public.company (company_id, company_name) VALUES (613, 'CEO');
INSERT INTO public.company (company_id, company_name) VALUES (982, 'Aspen Analytics');
INSERT INTO public.company (company_id, company_name) VALUES (983, 'Coffey Communications');
INSERT INTO public.company (company_id, company_name) VALUES (989, 'rebelstack');
INSERT INTO public.company (company_id, company_name) VALUES (914, 'Lewis Builders');
INSERT INTO public.company (company_id, company_name) VALUES (926, 'Caruso Builders');
INSERT INTO public.company (company_id, company_name) VALUES (980, 'QC Kinetix');
INSERT INTO public.company (company_id, company_name) VALUES (32, 'Front-End Test Company');
INSERT INTO public.company (company_id, company_name) VALUES (977, 'Boren Construction');
INSERT INTO public.company (company_id, company_name) VALUES (1008, '98 Ventures');
INSERT INTO public.company (company_id, company_name) VALUES (906, 'Highland Construction');
INSERT INTO public.company (company_id, company_name) VALUES (1009, 'Pillar Central');
INSERT INTO public.company (company_id, company_name) VALUES (978, 'Ardmor Windows and Doors');
INSERT INTO public.company (company_id, company_name) VALUES (988, 'Silva Construction Group');
INSERT INTO public.company (company_id, company_name) VALUES (1005, 'Ascent Bio-Nano Technologies');
INSERT INTO public.company (company_id, company_name) VALUES (1004, 'Mistake Company2');
INSERT INTO public.company (company_id, company_name) VALUES (1002, 'New Interview');
INSERT INTO public.company (company_id, company_name) VALUES (1003, 'AAA Inter com (interview templates testing)');
INSERT INTO public.company (company_id, company_name) VALUES (1010, 'Wise Auto Group');
INSERT INTO public.company (company_id, company_name) VALUES (1011, 'JLV Construction');
INSERT INTO public.company (company_id, company_name) VALUES (911, 'Kitchen Tune Up OH');
INSERT INTO public.company (company_id, company_name) VALUES (990, 'Healthy Home Co. ');
INSERT INTO public.company (company_id, company_name) VALUES (972, 'Huseby Homes');
INSERT INTO public.company (company_id, company_name) VALUES (938, 'JPH Design Build ');
INSERT INTO public.company (company_id, company_name) VALUES (940, 'MGD Builders');
INSERT INTO public.company (company_id, company_name) VALUES (922, 'Alair Homes Hunt Country');
INSERT INTO public.company (company_id, company_name) VALUES (929, 'Choice Builders');
INSERT INTO public.company (company_id, company_name) VALUES (928, 'CRC Builders');
INSERT INTO public.company (company_id, company_name) VALUES (944, 'Southcoast Kitchens ');
INSERT INTO public.company (company_id, company_name) VALUES (970, 'Alair Homes: Decatur');
INSERT INTO public.company (company_id, company_name) VALUES (935, 'SeaCoast Homes');
INSERT INTO public.company (company_id, company_name) VALUES (924, 'Trendsetter Homes');
INSERT INTO public.company (company_id, company_name) VALUES (1006, 'G&L and Sons Renovations, LLC');
INSERT INTO public.company (company_id, company_name) VALUES (946, 'Jason Thomas Homes');
INSERT INTO public.company (company_id, company_name) VALUES (1017, 'Back Bay Investment Group');
INSERT INTO public.company (company_id, company_name) VALUES (1012, 'Sweeney Restoration ');
INSERT INTO public.company (company_id, company_name) VALUES (950, 'Peavy Homes');
INSERT INTO public.company (company_id, company_name) VALUES (1018, 'North American Risk Services');
INSERT INTO public.company (company_id, company_name) VALUES (951, 'Readdick Construction');
INSERT INTO public.company (company_id, company_name) VALUES (1019, 'Carvajal Agency (AIL)');
INSERT INTO public.company (company_id, company_name) VALUES (1013, 'Alair Homes: Charlotte, NC');
INSERT INTO public.company (company_id, company_name) VALUES (1020, 'Inter Generic (Test)');
INSERT INTO public.company (company_id, company_name) VALUES (1014, 'Fletco Construction');
INSERT INTO public.company (company_id, company_name) VALUES (1007, 'Star Construction Company');
INSERT INTO public.company (company_id, company_name) VALUES (953, 'Tom Curren Companies');
INSERT INTO public.company (company_id, company_name) VALUES (1015, 'Inter sht. (Test)');
INSERT INTO public.company (company_id, company_name) VALUES (1016, 'Advanced Digital Media Services');